# Generated by Django 6.0.4 on 2026-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_trainingsession_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
