# Generated by Django 6.0.4 on 2026-05-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_userprofile_role_userprofile_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('player', 'Player'), ('parent', 'Parent')], default='player', max_length=20),
        ),
    ]
