# Generated by Django 6.0.4 on 2026-05-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('parent', 'Parent'), ('player', 'Player')], default='player', max_length=20),
        ),
    ]
